### ISSUE TITLE
do.sh doesn't exist

### ISSUE THREAD

**Issue by estark37** [chromium/suspicious-site-reporter#15]
The build instructions say to run do.sh, but that script doesn't exist in the repo. Forgot to check it in?

Also, is it possible to run the tests from this repo?

**Comment by livvielin** [comment]
do.sh should be in the extension directory

No, still not possible to run the tests from this repo, unfortunately. I have that on my TODO list, though it's been somewhat low priority--but maybe I should up the priority on that since it's certainly not ideal.

**Comment by livvielin** [comment]
Added issue #16 to track test running script

**Comment by estark37** [comment]
Oh that's embarrassing, I didn't read the instructions. Sorry for the noise!
