### ISSUE TITLE
avoiding brief flash of orange flag

### ISSUE THREAD

**Issue by roycewilliams** [chromium/suspicious-site-reporter#18]
In the latest version at this writing, if I go to a page that's not in the top 5K but has no other issues, the flag flashes orange (briefly, but still noticeably) before turning grey - almost (this is conjecture) as if the default is orange until the top-5K list is consulted.

Can the "default" be grey instead, or otherwise managed to avoid the Flash Of Orange Flag (FOOF)? ;)

**Comment by ericlaw1979** [comment]
Seems like this could be fixed by putting this inside the `browser_action` portion of the manifest?
```
   "default_icon": {
        "16": "images/grayflag16.png",
        "48": "images/grayflag48.png",
        "128": "images/grayflag128.png"
    }
```

**Comment by livvielin** [comment]
Yup, let's change the default to gray like Eric suggested.
