### ISSUE TITLE
Suspicious site reporter overrides "hide url schemes" flag in Chrome

### ISSUE THREAD

**Issue by LucasDiTomase** [chromium/suspicious-site-reporter#26]
This happens on latest version of Stable and Canary Google Chrome

When the extension is enabled, my flags no longer work

![Captura de Pantalla 2019-07-27 a la(s) 08 32 02](https://user-images.githubusercontent.com/46760897/61993908-451adb80-b049-11e9-95af-b1669f878d58.png)

![Captura de Pantalla 2019-07-27 a la(s) 08 32 25](https://user-images.githubusercontent.com/46760897/61993910-4946f900-b049-11e9-9100-f908fe5e30a2.png)

![Captura de Pantalla 2019-07-27 a la(s) 08 32 15](https://user-images.githubusercontent.com/46760897/61993911-4ba95300-b049-11e9-9c67-78d1d346ba14.png)

But when I disable the extension, the flags are working as intended again

![Captura de Pantalla 2019-07-27 a la(s) 08 32 33](https://user-images.githubusercontent.com/46760897/61993913-5cf25f80-b049-11e9-9ef3-1598ed7f843a.png)

![Captura de Pantalla 2019-07-27 a la(s) 08 33 15](https://user-images.githubusercontent.com/46760897/61993915-5f54b980-b049-11e9-8a24-ac5d55e3e0b0.png)

I made sure that the Google`s Suspicious site reporter is the responsible for this behavior

**Comment by livvielin** [comment]
Hi! Thanks for filing. This works as intended--we want to give users the most information possible to make a decision on whether the site is suspicious, including showing the full URL. We do this by preventing URL elisions in Chrome when the extension is enabled. I'll close out this bug for now, but feel free to reopen if you have any questions or concerns about this feature.

**Comment by ericlaw1979** [comment]
https://cs.chromium.org/chromium/src/chrome/browser/ui/toolbar/chrome_location_bar_model_delegate.cc?l=80&rcl=390b11af93e5be31dda6e46a056d5eed60277f09

**Comment by ericlaw1979** [comment]
The presence of this extension also seems to override chrome://flags/#enable-query-in-omnibox
