### ISSUE TITLE
Regression: No longer works in MS Edge (Chrome OK)

### ISSUE THREAD

**Issue by ericlaw1979** [chromium/suspicious-site-reporter#50]
v1.1.9 seems to fail in Microsoft Edge. Possibly due to refactoring and unavailability of the SafeBrowsing private API?

![image](https://user-images.githubusercontent.com/4192774/63989397-d0065000-caa5-11e9-8aff-2bb669e22671.png)

![image](https://user-images.githubusercontent.com/4192774/63989389-c7157e80-caa5-11e9-87bc-136b3c8b391d.png)

![image](https://user-images.githubusercontent.com/4192774/63989502-28d5e880-caa6-11e9-9a3a-31effb77ef7c.png)

**Comment by ericlaw1979** [comment]
https://github.com/chromium/suspicious-site-reporter/pull/44/files#diff-b927923d29083160dabd5cfeeda3c3d0R183 seems like a likely culprit.

**Comment by ericlaw1979** [comment]
Notably, the extension does not have this problem if you download the source from GitHub and compile it locally; the local version shows

|'safeBrowsingPrivate' is not allowed for specified extension ID.|

while the official version does not. So it seems likely to be inside an safeBrowsingPrivate block.

**Comment by ericlaw1979** [comment]
In Chrome's safeBrowsingPrivate API, we have [this](https://cs.chromium.org/chromium/src/chrome/browser/extensions/api/safe_browsing_private/safe_browsing_private_api.cc?l=57&rcl=d7e125903aa9c3cff56a1a57a6ee7bdd868acd5d)
```
if (!SafeBrowsingNavigationObserverManager::IsEnabledAndReady(profile))
    return RespondNow(NoArguments());
```
whereas the webStorePrivate version of getReferrerChain does this:

```
if (!SafeBrowsingNavigationObserverManager::IsEnabledAndReady(profile))
    return RespondNow(ArgumentList(
        api::webstore_private::GetReferrerChain::Results::Create("")));
```

**Comment by livvielin** [comment]
v1.20 with your patch is now in the webstore--let me know if there are still issues Edge! Thanks!

**Comment by ericlaw1979** [comment]
v1.2 looks good in Edge. Thanks!
