### ISSUE TITLE
Move the build to webpack and enable source mapping in browser for better debugging experience

### ISSUE THREAD

**Issue by JSSaini07** [chromium/suspicious-site-reporter#56]
Currently if you open the background script for debugging it is minified and hard to debug, I'd like to move the build process to webpack and enable source mapping in order to enhance debugging experience.

**Comment by JSSaini07** [comment]
@livvielin I'd be happy to work on this

**Comment by livvielin** [comment]
Thanks for the suggestion! We currently do an internal (Google/Bazel-like) build, so unfortunately I'm not sure that this would really work here. I'll close this issue for now, but feel free to re-open if you have additional thoughts.
