### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by phgmacedo** [chromium/suspicious-site-reporter#58]
This extension [was pointed out by google product manager Emily Stark](https://twitter.com/estark37/status/1191474217897750528?s=20) at at estark@google.com to be designed to allow powers users to show the full unedited and unelided URL.

But the extension does more that that. 

On [comment 5](https://bugs.chromium.org/p/chromium/issues/detail?id=1033076#c5), from the chromium issue, the product manager requests that users report specific bug reports about the extension in the github tracker for the extension. 

What the user wants:
To display the full, unedited, unaltered, unelided URL.

Solution offered by the google product manager:
Install the suspicious site reporter extension

Here is a repro:
1. Install the extension

Results:
The extension increases memory usage by 54 MB.

**Comment by pedrogarcia** [comment]
![emstark_bloated_extension](https://user-images.githubusercontent.com/2473545/70734297-bf8f8380-1cea-11ea-8db9-8902b0f49ee0.png)

**Comment by Ariefiswahyudi** [comment]
Duplicate of #65

**Comment by Ariefiswahyudi** [comment]
Hello world
