### ISSUE TITLE
Allow user to see and copy full URLs of Referrer Chain

### ISSUE THREAD

**Issue by jidanni** [chromium/suspicious-site-reporter#67]
The user cannot see the full URLs of the Referrer Chain.
![20635-0](https://user-images.githubusercontent.com/1230959/84529834-b7a1b200-ad14-11ea-8fbd-1bf6054cb450.jpg)
Nor can he copy them.
Nor can he generate a link preview of them in the lower left corner of the browser.

The best he can do is cross his fingers and hope for the best and click on them.

This extension should not only be for sending info to Google.
Sometimes the user would like to know what he will be sending.
In fact I was told to install this extension as a way to see what page referred another page...

**Comment by livvielin** [comment]
You should be able to expand the full URL by clicking on the individual URL in the preview. Since the main purpose is to see which URLs would be sent to Google, the copying feature isn't a huge priority, so closing this issue.

**Comment by jidanni** [comment]
Yes it turns out one clicks a link to see a preview. But that is a very dangerous precedent to set, and the first time I have ever encountered it.

Going this route, soon users of various apps won't know which clicks "commit" (to visiting a page, with all concomitant dangers) and which clicks just expand (so one can see the full URL to decide if one wants to "commit." )

**Comment by jidanni** [comment]
I would allow the box to be stretched from the bottom right corner, (like these GitHub comment boxes when editing.)

**Comment by jidanni** [comment]
Currently even if we click a URL, all we can do is see the rest of it. It would be useful if we could at least highlight and copy it as text.
Also perhaps add checkboxes that could allow the user to exclude some URLs from being sent.

**Comment by jidanni** [comment]
In fact right clicking on one of the URLs and choosing Copy Link Address always copies "chrome-extension://jknemblkbdhdcpllfgbfekkdciegfboi/popup.html#" instead of the URL we are "on" (hovering over). While technically correct, it is rather a pity. It would be much more useful if we could copy the URL we are "on". Thanks.
