### ISSUE TITLE
This tool is not user friendly

### ISSUE THREAD

**Issue by MalikRumi** [chromium/suspicious-site-reporter#70]
I saw a site in my search results that just looked funny. I decided to take the chance and click on it, because I know I have seen the google blocking interstitial on sites like this. But the interstitial did not come up. My suspicions were immediately confirmed, because the site did NOT show the alleged content that made it come up in my search, and wanted to download something to my computer. But when I went looking for a way to report this, all I found was this: yet another tool to add to my browser!

All the suspicious site mechanism needs is a form for the reporting person to input the suspicious url. _That's_ _**it!**_ Then behind the scenes Google can do exactly the same things this stupid extension does. There is no need to burden good faith reporters with even more stuff!!! Seriously, are you expecting us to turn into full time reporters for you? Give us all a break!

On top of all that, the minute I changed tabs, the flag icon to activate this extension vanished! wtf is that?

_It gets worse._ In order to make a report, you apparently expect users to go back to the suspicious site so the extension can do it's thing!!! Why would you ask us do that? **_Why should we risk - again - god knows what that site will put on our computers?!_** Do you ever think about your end users other than as free labor and advertising targets?!

End of rant.

Here is the suspicious site as it appeared in my serps:

`Spacy multi label classification. Machine Learning for Text ...pxn.andoiddukagjinit.online › spacy-multi-label-classifica...
Video for sklearn tf-idf multi-label text document classification tutorials -sentiment -image
42:57
I am trying to do multi-class classification and using the crowdflower text ... Multi-Label Classification in ...
Oct 15, 2012 · Uploaded by PyConDE`

This was the 3rd result in a keyword search for "sklearn tf-idf multi-label text document classification tutorials -sentiment -image" after clicking the 'video' tab. 

This site was suspicious because the upload date is 2012 and spacy didn't debut until 2015. 
According to my Chrome history, the actual sites I was sent to were load14.biz and 0.load14.biz. I hope somebody somewhere does  something about this site... and your stupid extension.

**Comment by estark37** [comment]
Hello,
This tool is designed for people who routinely encounter suspicious sites that they want to report as they encounter them. If you'd like to simply report a URL via a webform without needing to visit the site, you may use https://safebrowsing.google.com/safebrowsing/report_phish/?hl=en or https://safebrowsing.google.com/safebrowsing/report_badware/?hl=en.

Please also review the Chromium code of conduct before filing further issues on this repo: https://chromium.googlesource.com/chromium/src/+/master/CODE_OF_CONDUCT.md
